# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib azidentity, .registration = TRUE
NULL

#' Get an access token using the default Azure credential chain.
#' @param scopes One or more Azure OAuth 2.0 scopes.
#' @return A scalar character access token.
#' @examples
#' \dontrun{
#' default_azure_credential("https://management.azure.com/.default")
#' }
#' @export
default_azure_credential <- function(scopes) .Call(wrap__default_azure_credential, scopes)

# nolint end
